### ISSUE TITLE
plans for this lib

### ISSUE THREAD

**Issue by jschoch** [hirocaster/surge#1]
Hello hirocaster,  I like some of the syntax for your ddb lib.  Can you share your plans for the future?

**Comment by hirocaster** [comment]
Thank contact. and sorry, slow replay message.

This is my plan
 - Using serge in my job now.
 - Will release 1.0.0 version surge. 1-2 month. 
   - Support Global/Local indexes now.
   - Support only basic data type(Scalar data types, Integer, String, Binary...etc) now
   - Not support,  (Multi-valued types) Number Set, String Set, Binary Set in DynamoDB
   - Maybe change namespaces(DDL,DML, etc)

That's all.
